apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /set-package-name-to-dir
  name: set-package-name-to-dir
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|set-package-name-to-dir
source: |-
  load("krmfn.star", "krmfn")

  def get_root_kptfile_path(resources):
    for r in resources:
      if krmfn.match_gvk(r, "kpt.dev/v1", "Kptfile"):
        return r["metadata"]["annotations"]["internal.config.kubernetes.io/package-path"].rpartition("/")[0]
    return {}

  def get_package_name(root_kptfile_path, resource_path, resource_name):
    full_resource_path = resource_path + "/" + resource_name
    relative_resource_path = full_resource_path.removeprefix(root_kptfile_path + "/")
    package_name = relative_resource_path.rpartition("/")[0].replace("/", "-slash-").lower()
    return package_name

  def set_package_name(resources, root_kptfile_path):
    for r in resources:
      resource_path = r["metadata"]["annotations"]["internal.config.kubernetes.io/package-path"]
      resource_name = r["metadata"]["annotations"]["config.kubernetes.io/path"]
      package_name = get_package_name(root_kptfile_path, resource_path, resource_name)

      if krmfn.match_gvk(r, "apps/v1", "Deployment") or krmfn.match_gvk(r, "v1", "Service"):
        r["metadata"]["name"] = package_name

      if krmfn.match_gvk(r, "kpt.dev/v1", "Kptfile"):
        r["metadata"]["name"] = package_name
        r["info"]["description"] = "This is a nginx deployment for " + package_name

      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "kptfile.kpt.dev"):
        r["data"]["name"] = package_name

  root_kptfile_path = get_root_kptfile_path(ctx.resource_list["items"])

  set_package_name(ctx.resource_list["items"], root_kptfile_path)
