apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-package-name-to-dir
  annotations:
    config.kubernetes.io/local-config: "true"

source: |-
  load("krmfn.star", "krmfn")

  def get_package_dir(resources):
    for r in resources:
      if krmfn.match_gvk(r, "kpt.dev/v1", "Kptfile"):
        if not "internal.kpt.dev/render-root-path" in r["metadata"]["annotations"]:
          render_root_path = r["metadata"]["annotations"]["internal.config.kubernetes.io/package-path"]
          r["metadata"]["annotations"]["internal.kpt.dev/render-root-path"] = render_root_path
          print ("render_root_path=" + render_root_path)
          return render_root_path.rpartition("/")[2].lower()
        else:
          render_root_path = r["metadata"]["annotations"]["internal.kpt.dev/render-root-path"]
          print ("render_root_path=" + render_root_path)
          return r["metadata"]["annotations"]["internal.config.kubernetes.io/package-path"].rpartition(render_root_path + "/")[2].replace("/", "-").lower()
    
    return {}

  def set_package_name(resources, package_name):
    for r in resources:
      if krmfn.match_gvk(r, "apps/v1", "Deployment") or krmfn.match_gvk(r, "v1", "Service"):
        r["metadata"]["name"] = package_name

      if krmfn.match_gvk(r, "kpt.dev/v1", "Kptfile"):
        r["metadata"]["name"] = package_name
        r["info"]["description"] = "This is a nginx deployment for " + package_name

      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "kptfile.kpt.dev"):
        r["data"]["name"] = package_name

  def clear_internal_annotations(resources):
    for r in resources:
      if "internal.kpt.dev/render-root-path" in r["metadata"]["annotations"]:
        r["metadata"]["annotations"].pop("internal.kpt.dev/render-root-path")

  package_dir = get_package_dir(ctx.resource_list["items"])

  print("setting package name to " + package_dir)

  set_package_name(ctx.resource_list["items"], package_dir)

  print("package name has been set to " + package_dir)

  clear_internal_annotations(ctx.resource_list["items"])
