apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /package-options
  name: package-options
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|package-options'
data:
  name: wonderful-feature-d-wf-dep-subpkg-2-d-wf-dep-subsubpkg-2-3
